# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 664c7442c43a6b734ae82f08297635b822fd5c25c06704d4e4e9e09143d61747d2b4c39facd517d01e84bf3a47b647bb23310edef67d992e4db2301c5e6a6688

test:
  secret_key_base: ebe4336010b8a62989dc98a12f0f5e6d311efa6c019b0153cecf3c21497c02bce271eaa3213964ae1ab364cca1545b208158d81cf068803ca87c9d962a3aa8a4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
